apiVersion: v1
kind: Service
metadata:
  name: svc-etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 2379

---

apiVersion: v1
kind: Endpoints
metadata:
  # 名称必须和 Service 一致
  name: svc-etcd
subsets:
  - addresses:
    - ip: 192.168.2.221
    - ip: 192.168.2.222
    ports:
    - port: 2379
      

