apiVersion: v1
kind: Pod
metadata:
  name: busybox-demo
spec:
  containers:
  - name: busybox
    image: busybox
    args: ["/bin/sh", "-c", "cd /data/config && cat config.yaml"]
    volumeMounts:
      - name: v-secret-demo
        mountPath: /data/config
  volumes:
    - name: v-secret-demo
      secret:
        secretName: secret-demo3
        items:
          - key: config.yaml
            path: config.yaml