apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
spec:
  volumes:
    - name: web
      persistentVolumeClaim:
        claimName: pvc-openebs
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: web
        mountPath: /usr/share/nginx/html
  
