apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nfs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: web
            mountPath: /usr/share/nginx/html
      volumes:
        - name: web
          persistentVolumeClaim:
            claimName: pvc-nfs
